ALTER SYSTEM SET DB_CREATE_FILE_DEST = '/home/oracle/';
SET SERVEROUTPUT ON;

BEGIN
    EXECUTE IMMEDIATE 'CREATE PLUGGABLE DATABASE HOTEL ADMIN USER master IDENTIFIED BY master';
    DBMS_OUTPUT.PUT_LINE('The PDB is created successfully!!');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('The PDB is already exists, so do not create a new one!!');
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER PLUGGABLE DATABASE HOTEL OPEN';
    DBMS_OUTPUT.PUT_LINE('Open PDB successfully!!');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('The PDB is already opened, so do not do any operation!!');
END;
/

ALTER SESSION SET CONTAINER = HOTEL;

-- DROP USER HOTEL_PUBLIC CASCADE;
BEGIN
    EXECUTE IMMEDIATE 'CREATE USER HOTEL_PUBLIC IDENTIFIED BY password';
    EXECUTE IMMEDIATE 'GRANT CREATE SESSION, CREATE TABLE, CREATE USER TO HOTEL_PUBLIC WITH ADMIN OPTION';
    EXECUTE IMMEDIATE 'GRANT DBA TO HOTEL_PUBLIC WITH ADMIN OPTION';
    EXECUTE IMMEDIATE 'GRANT SELECT ANY DICTIONARY TO HOTEL_PUBLIC WITH ADMIN OPTION';
    EXECUTE IMMEDIATE 'GRANT CONNECT TO HOTEL_PUBLIC WITH ADMIN OPTION';
    EXECUTE IMMEDIATE 'GRANT GRANT ANY ROLE TO HOTEL_PUBLIC';
    
    DBMS_OUTPUT.PUT_LINE('The Public Schema is created successfully!!');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('The Public Schema is already exists, so do not create a new one!!');
END;
/