CONNECT HOTEL_PUBLIC/password@localhost:1521/HOTEL;
SET SERVEROUTPUT ON;

/*
    Check connection availability
*/
SET SERVEROUTPUT ON

DECLARE
  v_service_name VARCHAR2(100);
BEGIN
  SELECT SYS_CONTEXT('USERENV', 'SERVICE_NAME') INTO v_service_name FROM DUAL;
  DBMS_OUTPUT.PUT_LINE('Service Name: ' || v_service_name);
END;
/
/*

    Create table in database

*/
--1
CREATE TABLE A_KHACHHANG(
    MAKH        VARCHAR2(10),
    HOTEN       NVARCHAR2(50),
    SDT         VARCHAR2(20),
    CCCD        VARCHAR2(12) ,
    DIACHI      NVARCHAR2(100),
    CONSTRAINT CCCD_KH_UNIQUE UNIQUE(CCCD),
    CONSTRAINT FK_KHACHHANG PRIMARY KEY (MAKH)
);
/
--2
CREATE TABLE A_NHANVIEN (
    MANV         VARCHAR2(10),
    TENNV        VARCHAR2(50),
    PHAI         VARCHAR2(10),
    NGAYSINH     DATE,
    DIACHI       VARCHAR2(100),
    SODT         VARCHAR2(20),
    EMAIL        VARCHAR2(100),
    VAITRO       NVARCHAR2(20), 
    CCCD        VARCHAR2(12) ,    
    CONSTRAINT CCCD_NV_UNIQUE UNIQUE(CCCD),
    CONSTRAINT PK_NHANVIEN PRIMARY KEY (MANV)
);
/
--3
CREATE TABLE A_PHONG(
    MAPHONG         VARCHAR2(10),
    LOAIPHONG       NVARCHAR2(20),
    GIA             NUMBER(10, 0),
    TINHTRANG       NUMBER(1),
    SONGUOI         INTEGER,
    CONSTRAINT PK_PHONG PRIMARY KEY(MAPHONG)
);
/
--4
CREATE TABLE A_TOUR(
    MATOUR      VARCHAR2(10),
    TENTOUR     NVARCHAR2(50),
    DIADIEM     NVARCHAR2(100),
    CONSTRAINT PK_TOUR PRIMARY KEY (MATOUR)
);
/
--5
CREATE TABLE A_DVLUHANH(
    MADV        VARCHAR2(10),
    TENDV       NVARCHAR2(100),
    MATOUR      VARCHAR2(10),
    CONSTRAINT PK_DVLUHANH PRIMARY KEY (MADV)
);
/
--6
CREATE TABLE A_DICHVU(
    MADV    VARCHAR2(10),
    TENDV   NVARCHAR2(30),
    GIA     DECIMAL(10,0),
    CONSTRAINT PK_DICHVU PRIMARY KEY (MADV)
);
/
--7
CREATE TABLE A_SANPHAM(
    MASP        VARCHAR2(10),
    TENSP       NVARCHAR2(50),
    GIA         DECIMAL(10,0),
    CONSTRAINT PK_SANPHAM PRIMARY KEY (MASP)
);
/
--8
CREATE TABLE A_DISCOUNT(
    MAKM    NVARCHAR2(10),
    TENKM   NVARCHAR2(100),
    MOTA    NVARCHAR2(100),
    NGAYHETHAN DATE,
    CONSTRAINT PK_DISCOUNT PRIMARY KEY(MAKM)
);
/
--9
CREATE TABLE A_SANPHAM_PHONG(
    MAPHONG     VARCHAR2(10),
    MASP        VARCHAR2(10),
    SOLUONG     NUMBER(2),
    CONSTRAINT PK_SP_PHONG PRIMARY KEY (MASP, MAPHONG)
);
/
--10
CREATE TABLE A_PHIEUDATPHONG(
    MAPHIEU         VARCHAR2(10),
    NGAYBD          DATE,
    NGAYKT          DATE,
    LOAITHANHTOAN   NVARCHAR2(20),
    MANV            VARCHAR2(10),
    NGAYLAP         DATE,
    MAKH            VARCHAR2(10),
    TONGTIEN        DECIMAL(10,0),
    DATHANHTOAN     DECIMAL(10,0),
    TraPhong number, --0 là chưa trả, 1 là trả rồi
    CONSTRAINT PL_PHIEUDATPHONG PRIMARY KEY(MAPHIEU)
);
/
--11
CREATE TABLE A_HOADON(
    MAHD        VARCHAR2(10),
    TONGTIEN    DECIMAL(10,0),
    NGAYLAP     DATE,
    MANV        VARCHAR2(10),
    CONSTRAINT PK_HOADON PRIMARY KEY (MAHD)
);
--12
/
CREATE TABLE A_PHIEUDV(
    MAPHIEU     VARCHAR2(10),
    TONGTIEN    DECIMAL(10,0),
    MANV        VARCHAR2(10),
    NGAYLAP     DATE,
    CONSTRAINT PK_PHIEUDV PRIMARY KEY (MAPHIEU)
);
--13
/
CREATE TABLE A_CHITIETPHIEUDV(
    MAPHIEU     VARCHAR2(10),
    MADV        VARCHAR2(10),
    SOTIEN      DECIMAL(10,0),
    CONSTRAINT PK_CTDV PRIMARY KEY (MAPHIEU, MADV)
);
--14
/
CREATE TABLE A_KH_DOAN(
    MAKH    VARCHAR2(10),
    MADOAN  VARCHAR2(10),
    CONSTRAINT PK_KH_DOAN PRIMARY KEY (MAKH, MADOAN)
);
--15
/
CREATE TABLE A_DOAN(
    MADOAN      VARCHAR2(10),
    TENDOAN     NVARCHAR2(100),
    TENHDVIEN   NVARCHAR2(100),
    CONSTRAINT PK_DOAN PRIMARY KEY (MADOAN)
);

/
-- proc
create or replace procedure UpdateTongTienPhieuDV( P_maPhieu IN varchar2)
is 
    v_count1 INTEGER;
begin 

    SELECT count(*) INTO v_count1 FROM HOTEL_PUBLIC.A_PHIEUDV A, HOTEL_PUBLIC.A_CHITIETPHIEUDV C 
    WHERE A.MAPHIEU = C.MAPHIEU AND A.MAPHIEU = P_maPhieu AND A.TINHTRANG = 'Chưa thanh toán';
    
    update A_PHIEUDV set TONGTIEN = v_count1*300000 where MAPHIEU = P_maPhieu;
    
end;
-- user NV041
grant select on  A_PHONG to NV041;
grant select, insert, update on A_KHACHHANG to NV041;
grant select, insert, update on A_PHONG to NV041;
grant select, insert, update on A_PHIEUDATPHONG to NV041;
grant select, insert, update on A_PHIEUDV to NV041;
grant select, insert, update on A_DICHVU to NV041;
grant select, insert, update, delete on A_CHITIETPHIEUDV to NV041;
grant execute on UpdateTongTienPhieuDV to NV041;
